services:
  devtools:
    build: .
    volumes:
      - .:/app
      - node_modules_app:/app/node_modules
      - node_modules_backend:/app/backend/node_modules
      - node_modules_frontend:/app/frontend/node_modules
      - node_modules_api_serializers:/app/packages/api-serializers/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_typing_core:/app/packages/typing-core/node_modules
    tty: true

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/app
      - node_modules_backend:/app/backend/node_modules
      - node_modules_api_serializers:/app/packages/api-serializers/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_typing_core:/app/packages/typing-core/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@database:5432/postgres
    command: bash -c 'cd backend && if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && npm run db-push && cd .. && npm run dev:backend'
    depends_on:
      - database
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - .:/app
      - node_modules_frontend:/app/frontend/node_modules
      - node_modules_api_serializers:/app/packages/api-serializers/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_typing_core:/app/packages/typing-core/node_modules
    ports:
      - 5173:5173
    command: bash -c 'cd frontend && if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && cd .. && npm run dev:frontend'

volumes:
  node_modules_app:
  node_modules_backend:
  node_modules_frontend:
  node_modules_api_serializers:
  node_modules_api_types:
  node_modules_question_sets:
  node_modules_typing_core:
