services:
  - type: web
    name: typing-game
    env: static
    buildCommand: npm run ci:packages && npm run build:packages && cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    domains:
      - typing.utcode.net
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /
    envVars:
      - key: VITE_API_ENDPOINT
        value: https://api.typing.utcode.net/api
  - type: web
    name: typing-game-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm run ci:packages && npm run build:packages && cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start
    domains:
      - api.typing.utcode.net
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        value: https://typing.utcode.net
