import { TypingOriginTask } from "@typing/core";

const TYPING_TASK_COLLECTIONS: {
  id: string;
  title: string;
  typingTasks: TypingOriginTask[];
}[] = [
  {
    id: "0b6d3308-5670-41fc-bb3e-590a4d34d754",
    title: "Basic",
    typingTasks: [
      {
        word: "Hello World",
        kana: "",
        spellingList: ["Hello World"],
      },
      {
        word: "World",
        kana: "",
        spellingList: ["World"],
      },
      {
        word: "世界",
        kana: "せかい",
        spellingList: ["sekai"],
      },
      {
        word: "ABC",
        kana: "",
        spellingList: ["ABC"],
      },
    ],
  },
  {
    id: "23huh40ih5670-41fchua2uh590a4d34d754",
    title: "魚の名前",
    typingTasks: [
      { word: "鮪", kana: "まぐろ", spellingList: ["maguro"] },
      { word: "鯖", kana: "さば", spellingList: ["saba"] },
      { word: "鰯", kana: "いわし", spellingList: ["iwashi"] },
      { word: "鱈", kana: "たら", spellingList: ["tara"] },
      { word: "鮭", kana: "さけ", spellingList: ["sake"] },
      { word: "鰹", kana: "かつお", spellingList: ["katsuo"] },
      { word: "鯏", kana: "あさり", spellingList: ["asari"] },
      { word: "鰈", kana: "かれい", spellingList: ["karei"] },
      { word: "鰒", kana: "ふぐ", spellingList: ["fugu"] },
      { word: "鮎", kana: "あゆ", spellingList: ["ayu"] },
      { word: "鰻", kana: "うなぎ", spellingList: ["unagi"] },
      { word: "鯱", kana: "しゃち", spellingList: ["shachi"] },
      { word: "鮒", kana: "ふな", spellingList: ["funa"] },
      { word: "鰌", kana: "どじょう", spellingList: ["dojo"] },
      { word: "鰕", kana: "えび", spellingList: ["ebi"] },
      { word: "鯨", kana: "くじら", spellingList: ["kujira"] },
      { word: "鰍", kana: "かじか", spellingList: ["kajika"] },
      { word: "鮴", kana: "めばる", spellingList: ["mebaru"] },
      { word: "鯉", kana: "こい", spellingList: ["koi"] },
      { word: "鰆", kana: "さわら", spellingList: ["sawara"] },
      { word: "鰊", kana: "にしん", spellingList: ["nishin"] },
      { word: "鰤", kana: "ぶり", spellingList: ["buri"] },
      { word: "鱚", kana: "きす", spellingList: ["kisu"] },
      { word: "鱧", kana: "はも", spellingList: ["hamo"] },
      { word: "鱶", kana: "ふか", spellingList: ["huka"] },
      { word: "鱸", kana: "すずき", spellingList: ["suzuki"] },
      { word: "鱷", kana: "わに", spellingList: ["wani"] },
      { word: "鮫", kana: "さめ", spellingList: ["same"] },
      { word: "鮗", kana: "このしろ", spellingList: ["konosiro"] },
      { word: "鯛", kana: "たい", spellingList: ["tai"] },
    ],
  },
  {
    id: "9d6156fe-d4c1-4c38-8152-f313cf64020d",
    title: "都道府県",
    typingTasks: [
      { word: "北海道", kana: "ほっかいどう", spellingList: ["hokkaido"] },
      { word: "青森県", kana: "あおもりけん", spellingList: ["aomoriken"] },
      { word: "岩手県", kana: "いわてけん", spellingList: ["iwateken"] },
      { word: "宮城県", kana: "みやぎけん", spellingList: ["miyagiken"] },
      { word: "秋田県", kana: "あきたけん", spellingList: ["akitaken"] },
      { word: "山形県", kana: "やまがたけん", spellingList: ["yamagataken"] },
      { word: "福島県", kana: "ふくしまけん", spellingList: ["fukushimaken"] },
      { word: "茨城県", kana: "いばらきけん", spellingList: ["ibarakiken"] },
      { word: "栃木県", kana: "とちぎけん", spellingList: ["tochigiken"] },
      { word: "群馬県", kana: "ぐんまけん", spellingList: ["gunmaken"] },
      { word: "埼玉県", kana: "さいたまけん", spellingList: ["saitamaken"] },
      { word: "千葉県", kana: "ちばけん", spellingList: ["chibaken"] },
      { word: "東京都", kana: "とうきょうと", spellingList: ["toukyouto"] },
      { word: "神奈川県", kana: "かながわけん", spellingList: ["kanagawaken"] },
      { word: "新潟県", kana: "にいがたけん", spellingList: ["niigataken"] },
      { word: "富山県", kana: "とやまけん", spellingList: ["toyamaken"] },
      { word: "石川県", kana: "いしかわけん", spellingList: ["ishikawaken"] },
      { word: "福井県", kana: "ふくいけん", spellingList: ["fukuiken"] },
      { word: "山梨県", kana: "やまなしけん", spellingList: ["yamanashiken"] },
      { word: "長野県", kana: "ながのけん", spellingList: ["naganoken"] },
      { word: "岐阜県", kana: "ぎふけん", spellingList: ["gifuken"] },
      { word: "静岡県", kana: "しずおかけん", spellingList: ["shizuokaken"] },
      { word: "愛知県", kana: "あいちけん", spellingList: ["aichiken"] },
      { word: "三重県", kana: "みえけん", spellingList: ["mieken"] },
      { word: "滋賀県", kana: "しがけん", spellingList: ["shigaken"] },
      { word: "京都府", kana: "きょうとふ", spellingList: ["kyoutofu"] },
      { word: "大阪府", kana: "おおさかふ", spellingList: ["osakafu"] },
      { word: "兵庫県", kana: "ひょうごけん", spellingList: ["hyougoken"] },
      { word: "奈良県", kana: "ならけん", spellingList: ["naraken"] },
      { word: "和歌山県", kana: "わかやまけん", spellingList: ["wakayamaken"] },
      { word: "鳥取県", kana: "とっとりけん", spellingList: ["tottoriken"] },
      { word: "島根県", kana: "しまねけん", spellingList: ["shimaneken"] },
      { word: "岡山県", kana: "おかやまけん", spellingList: ["okayamaken"] },
      { word: "広島県", kana: "ひろしまけん", spellingList: ["hiroshimaken"] },
      { word: "山口県", kana: "やまぐちけん", spellingList: ["yamaguchiken"] },
      { word: "徳島県", kana: "とやまけん", spellingList: ["tokushimaken"] },
      { word: "香川県", kana: "かがわけん", spellingList: ["kagawaken"] },
      { word: "愛媛県", kana: "えひめけん", spellingList: ["ehimeken"] },
      { word: "高知県", kana: "こうちけん", spellingList: ["kouchiken"] },
      { word: "福岡県", kana: "ふくおかけん", spellingList: ["fukuokaken"] },
      { word: "佐賀県", kana: "さがけん", spellingList: ["sagaken"] },
      { word: "長崎県", kana: "ながさきけん", spellingList: ["nagasakiken"] },
      { word: "熊本県", kana: "くまもとけん", spellingList: ["kumamotoken"] },
      { word: "大分県", kana: "おおいたけん", spellingList: ["ooitaken"] },
      { word: "宮崎県", kana: "みやざきけん", spellingList: ["miyazakiken"] },
      {
        word: "鹿児島県",
        kana: "かごしまけん",
        spellingList: ["kagoshimaken"],
      },
      { word: "沖縄県", kana: "おきなわけん", spellingList: ["okinawaken"] },
    ],
  },

  {
    id: "51710ca4-7b81-4e17-9389-384dbf6d75dc",
    title: "Fruits",
    typingTasks: [
      {
        word: "Apple",
        kana: "",
        spellingList: ["Apple"],
      },
      {
        word: "Banana",
        kana: "",
        spellingList: ["Banana"],
      },
      {
        word: "Cherry",
        kana: "",
        spellingList: ["Cherry"],
      },
      {
        word: "Durian",
        kana: "",
        spellingList: ["Durian"],
      },
    ],
  },
];

export default TYPING_TASK_COLLECTIONS;
