name: Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  render-awake:
    name: Render Awake
    runs-on: ubuntu-latest
    steps:
      - name: Install cURL
        run: sudo apt install curl
        shell: bash

      - name: Access to Render
        run: curl --silent --show-error https://api.typing.utcode.net
        shell: bash
